### PR TITLE
feat: added support for bentoml 1.0 with terraform

### PR DESCRIPTION
**Pull request by jjmachan**
Added a default template that generates a single EC2 instance with the bentoserver running.

### CODE REVIEW

**Comment by jjmachan** [comment]
@yubozhao There are a couple of things I wanted to make sure of before we merge it in.

- currently, I've disabled port 22 in the security group which makes it harder to debug but leaving that open is also a bad practice right?
- Right now there is a small delay between when the ec2 instance is in a "running" state and when the actual service is running. This is because the user_data script is running only after the instance is up and then proceeds to setup docker, aws-cli , pull the image and run the service. This mean if the user runs `bentoctl apply` and goes to the IP address that is given it will show a blank screen. It will take some time before it gets working. A mild problem

**Comment by jjmachan** [comment]
should also configure cloudwatch logs here too

**Comment by yubozhao** [comment]
@jjmachan Did you add the documentation for logging?

**Comment by jjmachan** [comment]
added the documentation for logging and updated the quickstart too. Feel free to merge it if the README looks good

**Pull request merged**
